// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPkdUqwnbz2hiBUIxgsoj_JZxuc7OFI6E',
    appId: '1:677499858056:web:dc717675548c7a780c833d',
    messagingSenderId: '677499858056',
    projectId: 'foodrec-e53ad',
    authDomain: 'foodrec-e53ad.firebaseapp.com',
    storageBucket: 'foodrec-e53ad.firebasestorage.app',
    measurementId: 'G-NTFS0PHV2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjRUXR32d1Hgd3JAx2R8PdE5ZEtrncNzY',
    appId: '1:677499858056:android:4a235fe1d3ad5d1b0c833d',
    messagingSenderId: '677499858056',
    projectId: 'foodrec-e53ad',
    storageBucket: 'foodrec-e53ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IutBtNNIESH8G7xyKv8QphHcJ653qGc',
    appId: '1:677499858056:ios:005a546f2ff57fb30c833d',
    messagingSenderId: '677499858056',
    projectId: 'foodrec-e53ad',
    storageBucket: 'foodrec-e53ad.firebasestorage.app',
    iosBundleId: 'com.example.foodrec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IutBtNNIESH8G7xyKv8QphHcJ653qGc',
    appId: '1:677499858056:ios:005a546f2ff57fb30c833d',
    messagingSenderId: '677499858056',
    projectId: 'foodrec-e53ad',
    storageBucket: 'foodrec-e53ad.firebasestorage.app',
    iosBundleId: 'com.example.foodrec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPkdUqwnbz2hiBUIxgsoj_JZxuc7OFI6E',
    appId: '1:677499858056:web:04c6d9ada761d9c40c833d',
    messagingSenderId: '677499858056',
    projectId: 'foodrec-e53ad',
    authDomain: 'foodrec-e53ad.firebaseapp.com',
    storageBucket: 'foodrec-e53ad.firebasestorage.app',
    measurementId: 'G-ZNH13XJ4YE',
  );
}
